export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  WALK_NOT_FOUND: 'WALK_NOT_FOUND',
  INVALID_WALK_STATE: 'INVALID_WALK_STATE',
  INVALID_PHOTO_COUNT: 'INVALID_PHOTO_COUNT',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  AI_ANALYSIS_FAILED: 'AI_ANALYSIS_FAILED',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  INVALID_TAG_SELECTION: 'INVALID_TAG_SELECTION',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  SEARCH_FAILED: 'SEARCH_FAILED',
  INSUFFICIENT_SEARCH_RESULTS: 'INSUFFICIENT_SEARCH_RESULTS',
  AI_RECOMMENDATION_FAILED: 'AI_RECOMMENDATION_FAILED',
  PERSISTENCE_FAILED: 'PERSISTENCE_FAILED',
  SAVE_FAILED: 'SAVE_FAILED',
  DELETE_FAILED: 'DELETE_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
